[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC"
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.9

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"
version = "1.0.3"

[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "windows-sys" },
    { name = "hermit-abi" }
]
