[package]
name = "asyncgit"
version = "0.8.1"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"
description = "allow using git2 in a asynchronous context"
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["concurrency","asynchronous"]
keywords = ["git"]

[dependencies]
scopetime = { path = "../scopetime", version = "0.1" }
git2 = { version = "0.13.6", default-features = false }
rayon-core = "1.7"
crossbeam-channel = "0.4"
log = "0.4"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.1"
invalidstring = { path = "../invalidstring", version = "0.1" }