[package]
name = "asyncgit"
version = "0.10.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"
description = "allow using git2 in a asynchronous context"
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["concurrency","asynchronous"]
keywords = ["git"]

[dependencies]
scopetime = { path = "../scopetime", version = "0.1" }
git2 = { version = "0.13", features = ["vendored-openssl"] }
rayon-core = "1.9"
crossbeam-channel = "0.5"
log = "0.4"
thiserror = "1.0"
url = "2.1.1"

[dev-dependencies]
tempfile = "3.1"
invalidstring = { path = "../invalidstring", version = "0.1" }
serial_test = "0.5.0"