name: CI

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly, stable, '1.65']
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: git submodule update --init --recursiv
      run: |
        git submodule update --init --recursive

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci
      with:
        shared-key: ${{ matrix.os }}-${{ env.cache-name }}-${{ matrix.rust }}

    - name: MacOS Workaround
      if: matrix.os == 'macos-latest'
      run: cargo clean -p serde_derive -p thiserror

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy

    - name: make rustup-install
      if: matrix.os != 'windows-latest'
      run: |
        make rustup-install

    - name: make rustup-target-add
      if: matrix.os != 'windows-latest'
      run: |
        make rustup-target-add

    - name: make cargo-b
      if: matrix.os != 'windows-latest'
      run: |
        make cargo-b || cargo b

    - name: make cargo-b-release
      if: matrix.os != 'windows-latest'
      run: |
        make cargo-b-release || cargo b --release

    - name: Run tests
      if: matrix.os != 'windows-latest'
      run: make test

    - name: make test-linux-musl
      if: matrix.os != 'windows-latest'
      run: make test-linux-musl

    - name: Run clippy
      if: matrix.os != 'windows-latest'
      run: |
        make clippy || cargo clippy

    - name: Build Release
      #if: matrix.os != 'windows-latest'
      run: make build-release || cargo b --release

    - name: Test Install
      #if: matrix.os != 'windows-latest'
      run: cargo install --path "." --force --locked

    - name: Binary Size (unix)
      if: matrix.os != 'windows-latest'
      run: |
        ls -l ./target/release/gnostr-tui

    - name: Binary Size (win)
      if: matrix.os == 'windows-latest'
      run: |
        ls -l ./target/release

    - name: Binary dependencies (mac)
      if: matrix.os == 'macos-latest'
      run: |
        otool -L ./target/release/gnostr-tui

    - name: Build MSI (windows)
      if: matrix.os == 'windows-latest'
      run: |
        cargo install cargo-wix --version 0.3.3
        cargo wix --version
        cargo wix -p gnostr-tui --no-build --nocapture --output ./target/wix/gnostr-tui.msi
        ls -l ./target/wix

  build-linux-musl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, stable, '1.65']
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci
      with:
        key: ubuntu-latest-${{ env.cache-name }}-${{ matrix.rust }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        targets: x86_64-unknown-linux-musl

    # The build would fail without manually installing the target.
    # https://github.com/dtolnay/rust-toolchain/issues/83
    - name: Manually install target
      if: matrix.os != 'windows-latest'
      run: rustup target add x86_64-unknown-linux-musl

    - name: Setup MUSL
      if: matrix.os != 'windows-latest'
      run: |
        sudo apt-get -qq install musl-tools
    - name: Build Debug
      if: matrix.os != 'windows-latest'
      run: |
        TARGET_CC=x86_64-linux-musl-gcc cargo build           --target x86_64-unknown-linux-musl
        make build-linux-musl-debug
        ./target/x86_64-unknown-linux-musl/debug/gnostr-tui --version
    - name: Build Release
      if: matrix.os != 'windows-latest'
      run: |
        TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl
        make build-linux-musl-release
        ./target/x86_64-unknown-linux-musl/release/gnostr-tui --version
        ls -l ./target/x86_64-unknown-linux-musl/release/gnostr-tui
    - name: Test
      if: matrix.os != 'windows-latest'
      run: |
        make test-linux-musl
    - name: Test Install
      if: matrix.os != 'windows-latest'
      run: cargo install --path "." --force --locked

  build-linux-arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, stable, '1.65']
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci
      with:
        key: ubuntu-latest-${{ env.cache-name }}-${{ matrix.rust }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Setup ARM toolchain
      if: matrix.os != 'windows-latest'
      run: |
        make rustup-target-add
        rustup target add aarch64-unknown-linux-gnu
        rustup target add armv7-unknown-linux-gnueabihf
        rustup target add arm-unknown-linux-gnueabihf

        curl -o $GITHUB_WORKSPACE/aarch64.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
        curl -o $GITHUB_WORKSPACE/arm.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz

        tar xf $GITHUB_WORKSPACE/aarch64.tar.xz
        tar xf $GITHUB_WORKSPACE/arm.tar.xz

        echo "$GITHUB_WORKSPACE/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu/bin" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf/bin" >> $GITHUB_PATH

    - name: Build Debug
      if: matrix.os != 'windows-latest'
      run: |
        make build-linux-arm-debug || cargo b
    - name: Build Release
      if: matrix.os != 'windows-latest'
      run: |
        make build-linux-arm-release || cargo b --release
        ls -l ./target/aarch64-unknown-linux-gnu/release/gnostr-tui || ls -l ./target/armv7-unknown-linux-gnueabihf/release/gnostr-tui || ls -l ./target/arm-unknown-linux-gnueabihf/release/gnostr-tui

  linting:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci
      with:
        key: ubuntu-latest-${{ env.cache-name }}-stable

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - run: cargo fmt -- --check

    - name: cargo-sort
      if: matrix.os != 'windows-latest'
      run: |
        cargo install cargo-sort --force
        cargo sort -c -w

    - name: cargo-deny install
      if: matrix.os != 'windows-latest'
      run: |
        cargo install --locked cargo-deny

    - name: cargo-deny licenses
      if: matrix.os != 'windows-latest'
      run: |
        cargo deny check licenses

    - name: cargo-deny bans
      if: matrix.os != 'windows-latest'
      run: |
        cargo deny check bans

  udeps:
    name: udeps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2
      env:
        cache-name: ci
      with:
        key: ubuntu-latest-${{ env.cache-name }}-nightly

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly

    - name: cargo-udeps
      if: matrix.os != 'windows-latest'
      run: |
        # cargo install --locked cargo-udeps
        cargo install --git https://github.com/est31/cargo-udeps --locked
        cargo +nightly udeps --all-targets

  sec:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - uses: rustsec/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ignore: RUSTSEC-2020-0071, RUSTSEC-2022-0004, RUSTSEC-2022-0011

  log-test:
    name: Changelog Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '10'
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Extract release notes
      id: extract_release_notes
      uses: ffurrer2/extract-release-notes@v1
      with:
        release_notes_file: ./release-notes.txt
    - uses: actions/upload-artifact@v3
      with:
        name: release-notes.txt
        path: ./release-notes.txt
